---
- name: Windows Patch Management
  hosts: windows
  tasks:
    - name: Check for available updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        state: searched
      register: update_search
    
    - name: Display available updates
      debug:
        msg: "Found {{ update_search.found_update_count }} updates"
    
    - name: Show update details
      debug:
        var: update_search.updates
      when: update_search.found_update_count > 0
