---
- name: Complete Windows Server Setup
  hosts: windows
  tasks:
    # System Configuration
    - name: Set timezone
      win_timezone:
        timezone: "Eastern Standard Time"
    
    - name: Configure Windows Updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        state: installed
        reboot: yes
    
    # User Management
    - name: Create service account
      win_user:
        name: svc_webapp
        password: "{{ service_password }}"
        state: present
        groups:
          - IIS_IUSRS
    
    # Windows Features
    - name: Install IIS features
      win_feature:
        name:
          - IIS-WebServerRole
          - IIS-WebServer
          - IIS-CommonHttpFeatures
          - IIS-HttpErrors
          - IIS-HttpRedirect
          - IIS-ApplicationDevelopment
          - IIS-NetFxExtensibility45
          - IIS-HealthAndDiagnostics
          - IIS-HttpLogging
          - IIS-Security
          - IIS-RequestFiltering
          - IIS-Performance
          - IIS-WebServerManagementTools
          - IIS-ManagementConsole
          - IIS-IIS6ManagementCompatibility
          - IIS-Metabase
          - IIS-ASPNET45
        state: present
    
    # Registry Configuration
    - name: Configure IIS registry settings
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\W3SVC\Parameters
        name: MaxRequestEntityAllowed
        data: 4294967295
        type: dword
    
    # File Operations
    - name: Create application directories
      win_file:
        path: "{{ item }}"
        state: directory
      loop:
        - C:\inetpub\logs\myapp
        - C:\inetpub\myapp\bin
        - C:\inetpub\myapp\config
    
    # Service Management
    - name: Configure IIS service
      win_service:
        name: W3SVC
        state: started
        start_mode: auto
        
    # Firewall Rules
    - name: Open HTTP port
      win_firewall_rule:
        name: HTTP-In
        localport: 80
        action: allow
        direction: in
        protocol: tcp
        state: present
